version: "3.5"

services:
  nuxt:
    build: .
    container_name: nuxt
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "admin-portal"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: true,
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - admin-portal:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80

volumes:
  admin-portal:
